image: adoptopenjdk/openjdk11-openj9:alpine

variables:
  GRADLE_CACHE: .cache/.gradle
  GRADLE_CMD: ./gradlew --no-daemon --console=plain -g $GRADLE_CACHE

cache:
  paths:
    - $GRADLE_CACHE

before_script:
  - chmod +x gradlew

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
  - $GRADLE_CMD clean assemble
  allow_failure: false

test:
  stage: test
  script:
    - $GRADLE_CMD build
  allow_failure: false
  artifacts:
    when: on_failure
    paths:
      - build/reports
      - '*/build/reports'
    expire_in: 1 month

  coverage: '/^Coverage:\s+(\d+(?:\.\d+)?)%/'

publish:
  stage: publish
  script:
    - $GRADLE_CMD publish
