image: adoptopenjdk/openjdk11-openj9:alpine

variables:
  GRADLE_OPTS: "--no-daemon --console=plain"

cache:
  paths:
    - /cache/.gradle

before_script:
  - chmod +x gradlew

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
  - ./gradlew -g /cache/.gradle clean assemble
  allow_failure: false

test:
  stage: test
  script:
    - ./gradlew -g /cache/.gradle test
  allow_failure: false
  artifacts:
    when: on_failure
    paths:
      - build/reports
      - '*/build/reports'
    expire_in: 1 month

  coverage: '/^Coverage:\s+(\d+(?:\.\d+)?)%/'

publish:
  stage: publish
  script:
    - ./gradlew -g /cache/.gradle publish
